apiVersion: v1
kind: Pod
metadata:
 name: web-server-pod
 labels:
  app: web-server-app01
  region: CA
  rack: r1
  version: "1.1"

spec:
  containers:
    - name: httpd
      image: httpd 
      ports:
      - containerPort: 80

