apiVersion: v1
kind: Service
metadata:
 name: webserver-server
 labels:
   app: webserver-service-label
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
  selector:
    version: "1.1"

