apiVersion: v1
kind: ReplicationController
metadata:
 name: webserver-rc
spec:
 replicas: 5
 selector: 
   app: lamp-appl
 template:
  metadata:
   labels:
    app: lamp-appl
    region: CA
    rack: r1
    version: "1.1"
  spec:
    containers:
    - name: webserver-php-conl
      image: httpd
      ports:
      - containerPort: 80

