apiVersion: v1
kind: ReplicationController
metadata:
 name: "oradb"
spec:
 replicas: 5
 selector:
   app: "oradb"
 template: 
  metadata:
    labels:
     app: "oradb"
  spec:
    containers:
    - image: "sath89/oracle-xe-11g"
      name: "oradb"

