apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo 
spec:
  ports:
  - name:  mongo-port
    port:  27017
    targetPort:  27017
  selector:
    name: mongo  
  type: LoadBalancer  