apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-cond-pod
  name: multi-cond-pod
spec:
  containers:
  - image: busybox
    name: main-container
    args: ["sleep 5555" ]
    volumeMounts: 
    - name: var-logs
      mountPath: /var/log
  - image: nginx
    name: sidecar-container
    ports:
     - containerPort: 80
    volumeMounts:
    - name: var-logs
      mountPath: /usr/share/nginx/html
  volumes:
    - name: var-logs
      emptyDir: {}
