apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-test
  name: busybox-test
spec:
  containers:
  - args:
    - bin/sh
    - -c
    - sleep 3600; ls
    image: busybox
    name: busybox1
  - args:
    - bin/sh
    - -c
    - echo "this is second container"
    image: busybox
    name: busybox2
  - args:
    - bin/sh
    - -c
    - sleep 90000; echo "This is third Container"
    image: busybox
    name: busybox3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
