apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx01
  name: nginx01
spec:
  containers:
  - image: nginx
    name: nginx01
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
