apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-13T03:25:53Z"
  labels:
    run: nginx01
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:run: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:run: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-09-13T03:25:53Z"
  name: nginx01
  namespace: default
  resourceVersion: "60562"
  selfLink: /api/v1/namespaces/default/services/nginx01
  uid: e681c74f-3212-4518-aadf-23d050e6dcf1
spec:
  clusterIP: 10.107.10.141
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31828
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx01
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
