apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx02
  name: nginx02
spec:
  containers:
  - image: nginx
    name: nginx02
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
