apiVersion: v1 
kind: ReplicationController
metadata:
 name: hello-world
spec:
 replicas: 2
 template:
   metadata:
     labels:
       app: hello-world
       region: CA
       rack: r1
       version: "1.1"
   spec:
     containers:
     - name: hello-world
       image: tutum/hello-world
       ports:
       - containerPort: 8080
         name: http
