apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypod
  name: mypod
spec:
  containers:
  - image: nginx
    name: mypod
    resources:
      requests:
        memory: "100m"
        cpu: "100m"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
