apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-cont-pod
  name: multi-cont-pod-2
spec:
  volumes:
  - name: var-logs
    emptyDir: {}    
  containers:
  - image: busybox
    name: main-container
    command: [ "/bin/sh" ]
    args: [ "-c", "while true; do echo 'test' >> /var/log/index.html; sleep 5; done" ]
    volumeMounts: 
    - name: var-logs
      mountPath: /var/log
  - image: nginx
    name: sidecar-container
    ports:
      - containerPort: 80
    volumeMounts: 
    - name: var-logs
      mountPath: /usr/share/nginx/html
  restartPolicy: Never
status: {}
