apiVersion: v1
kind: Pod
metadata:
  name: twocontainers
  labels:
    name: twocontainers
spec:
  containers:
  - name: msa1
    image: httpd
    ports:
      - containerPort: 80
  - name: shell
    image: centos:7
    command:
     - "bin/bash" 
     - "-c"   
     - "sleep 10000"