apiVersion: v1
kind: Pod
metadata:
  name: twocontainer
  labels:
    name: twocontainer
spec:
  containers:
  - name: msa1
    image: httpd
    ports:
      - containerPort: 80
    resources:
      limits:
        memory: "64Mi"  
        cpu: "500m"