version: '3.0'
services:
  webserver:
    image: wordpress
    container_name: wp_web
    ports: 
      - 8080:80
    links: 
      - dbserver: mysql
    environment: 
      WORDPRESS_DB_PASSWORD: 6zcznAEjLWp79P
  dbserver:
    image: mysql:latest
    container_name: wp_db
    environment: 
      MYSQL_ROOT_PASSWORD: 6zcznAEjLWp79P
      





